### ISSUE TITLE
Check if a socket is referenced nowhere and clean it (in addition of timeout)

### ISSUE THREAD

**Issue by Chat-Wane** [RAN3D/spray-wrtc#13]
Currently, we close the sockets using a timeout meaning that after a while, the socket is not used any longer. It could be possible to close it faster when no messages reference the socket. It requires to look carefully to whom is entitled to close a connection.

**Comment by folkvir** [comment]
With the new version,  a maximum of 2 sockets are allowed for a same peer, inview/outview. No longer an issue. Closed.
