### ISSUE TITLE
Forwarding routes without timeout

### ISSUE THREAD

**Issue by Chat-Wane** [RAN3D/spray-wrtc#8]
When an exchange is initiated by Peer Pi with the Peer Pj,  it asks to one of its neighbor to give it an offer ticket, then forwards it to Pj and expect Pj to give a stamped ticket in response. However, if Pj already knows the emitter of the offer, it directly adds it to its neighborhood (because it already has a working socket with him). Thus, no answer comes through Pi. Therefore, the forwarding route is kept while it should be cleaned at some point.
Note that the pending socket of the emitter is clean after 'timeout'.

**Comment by folkvir** [comment]
This part is done in n2n-wrtc now. With timeouts on the offers initiator and for the initiator of a bridgeIO/bridgeOI/bridgeOO/connect/connectToUs.
